version: "3.8"
services:
  db_cadastro:
    container_name: pg_db_cadastro_ifood
    image: postgres:latest
    environment:
      POSTGRES_USER: study
      POSTGRES_PASSWORD: study
      POSTGRES_DB: ifood-cadastro
    ports:
      - "5433:5432"
    networks:
      - ifood
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:9.0.3
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8190:8080"
    networks:
      - ifood
networks:
  ifood:
      driver: bridge
      name: network_ifood
