version: "3.8"
services:

  db_cadastro_ifood:
    container_name: db_cadastro_ifood
    image: postgres:14.1
    environment:
      POSTGRES_USER: study
      POSTGRES_PASSWORD: study
      POSTGRES_DB: ifood-cadastro
    volumes:
      - postgres_data_cadastro:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ifood

  db_marketplace_ifood:
    container_name: db_marketplace_ifood
    image: postgres:14.1
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: ifood-marketplace
    volumes:
      - postgres_data_marketplace:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - ifood

  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:9.0.3
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak_data:/var/lib/keycloak/data
      - keycloak_data_standalone:/opt/jboss/keycloak/standalone/data
    ports:
      - "8190:8080"
    networks:
      - ifood

  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.38
    volumes:
      - jaeger-storage:/badger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - ifood

  promethues_ifood:
    image: prom/prometheus:v2.39.0
    container_name: prometheus_ifood
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    network_mode: "host"

  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:9.1.7
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: "host"
    depends_on:
      - promethues_ifood

  activemq_ifood:
    container_name: activemq_ifood
    image: vromero/activemq-artemis:2.16.0
    networks:
      - ifood
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"

  #  artemis_ifood:
  #    container_name: activemq-artemis-broker
  #    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.9
  #    ports:
  #      - "8162:8161"
  #      - "61616:61616"
  #      - "5672:5672"
  #    environment:
  #      AMQ_USER: quarkus
  #      AMQ_PASSWORD: quarkus
  #    volumes:
  #      - activemq-storage:/var/lib/artemis
  #    networks:
  #      - ifood

  mongodb_ifood:
    container_name: mongodb_ifood
    image: mongo:6.0.3
    volumes:
      - mongodb-storage:/etc/mongo
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pedido
      MONGO_INITDB_ROOT_PASSWORD: pedido
      MONGO_INITDB_DATABASE: pedidos

  zookeeper_ifood:
    container_name: zookeeper_ifood
    image: debezium/zookeeper:1.9.6.Final
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka_ifood:
    container_name: kafka
    image: debezium/kafka:1.9.6.Final
    ports:
      - "9092:9092"
    links:
      - zookeeper_ifood
    environment:
      ZOOKEEPER_CONNECT: zookeeper_ifood:2181

  kafdrop_ifood:
    container_name: kafdrop_ifood
    image: obsidiandynamics/kafdrop:3.28.0
    environment:
      KAFKA_BROKERCONNECT: kafka_ifood:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka_ifood

  elastic_ifood:
    container_name: elastic_ifood
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: 0.50
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-storage:/usr/share/elasticsearch/data
    networks:
      - ifood

  kibana_ifood:
    container_name: kibana_ifood
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      SERVER_NAME: kibana.ifood.org
      ELASTICSEARCH_HOSTS: '["http://elastic_ifood:9200"]'
    networks:
      - ifood
    ports:
      - "5601:5601"
    depends_on:
     elastic_ifood:
       condition: service_started

networks:
  ifood:
    driver: bridge
    name: network_ifood

volumes:
  keycloak_data:
    name: keycloak_data
  keycloak_data_standalone:
    name: keycloak_data_standalone
  postgres_data_cadastro:
    name: postgres_data_cadastro
  postgres_data_marketplace:
    name: postgres_data_marketplace
  grafana-storage:
    name: grafana-storage
  jaeger-storage:
    name: jaeger-storage
  activemq-storage:
    name: activemq-storage
  mongodb-storage:
    name: mongodb-storage
  elasticsearch-storage:
    name: elasticsearch-storage
