version: "3.8"
services:

  db_cadastro_ifood:
    container_name: db_cadastro_ifood
    image: postgres:14.1
    environment:
      POSTGRES_USER: study
      POSTGRES_PASSWORD: study
      POSTGRES_DB: ifood-cadastro
    volumes:
      - postgres_data_cadastro:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ifood

  db_marketplace_ifood:
    container_name: db_marketplace_ifood
    image: postgres:14.1
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: ifood-marketplace
    volumes:
      - postgres_data_marketplace:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - ifood

  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:9.0.3
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak_data:/var/lib/keycloak/data
      - keycloak_data_standalone:/opt/jboss/keycloak/standalone/data
    ports:
      - "8190:8080"
    networks:
      - ifood

  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.38
    volumes:
      - jaeger-storage:/badger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - ifood

  promethues_ifood:
    image: prom/prometheus:v2.39.0
    container_name: prometheus_ifood
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    network_mode: "host"

  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:9.1.7
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: "host"
    depends_on:
      - promethues_ifood

networks:
  ifood:
      driver: bridge
      name: network_ifood

volumes:
  keycloak_data:
    name: keycloak_data
  keycloak_data_standalone:
    name: keycloak_data_standalone
  postgres_data_cadastro:
    name: postgres_data_cadastro
  postgres_data_marketplace:
    name: postgres_data_marketplace
  grafana-storage:
    name: grafana-storage
  jaeger-storage:
    name: jaeger-storage
