create table tb_localizacao
(
    id        bigint generated by default as identity
        constraint tb_localizacao_pkey
            primary key,
    latitude  double precision,
    longitude double precision
);

alter table tb_localizacao
    owner to study;