
quarkus:
  application:
    name: cadastro
  devservices:
    enabled: false
  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    username: study
    password: study
    jdbc:
      url: jdbc:postgresql://localhost:5433/ifood-cadastro

  hibernate-orm:
    database:
      generation: update
#      generation: drop-and-create
  http:
    port: ${SERVER_PORT:8090}
