quarkus:
  application:
    name: cadastro
  devservices:
    enabled: false
  datasource:
    devservices:
      enabled: false
  http:
    port: ${SERVER_PORT:8090}

  flyway:
    clean-at-start: false
    migrate-at-start: false