quarkus:
  application:
    name: IFOOD_PEDIDO
  mongodb:
    credentials:
      username: pedido
      password: pedido
    hosts: 127.0.0.1:27027
    database: admin
  http:
    port: ${SERVER_PORT:8092}
  devservices:
    enabled: false
  elasticsearch:
    hosts: localhost:9200
    protocol: http
  log:
    handler:
      gelf:
        enabled: true
        level: ALL
        host: localhost
        port: 12201
        filter-stack-trace: true
        skip-hostname-resolution: false
        origin-host: PEDIDO_IFOOD
        facility: jboss-logmanager

  vertx:
    cluster:
      host: PEDIDO
  smallrye-health:
    ui:
      enable: true

  kafka:
    health:
      enabled: true
kafka:
  bootstrap:
    servers: ${SERVER_KAKFA_SERVERS:localhost:9092}

amqp-host: localhost
amqp-port: 5672
amqp-username: admin
amqp-password: admin
mp:
  messaging:
    incoming:
      pedidosKfk:
        connector: smallrye-kafka
        value:
          deserializer: org.project.ifood.pedido.kafka.deserializer.PedidoDeserializer
        group:
          id: ${quarkus.application.name}
        auto:
          offset:
            reset: earliest
        health-enabled: true
        bootstrap:
          servers: ${PEDIDO_BOOTSTRAP_SERVERS:localhost:9092}