quarkus:
    application:
        name: marketplace-ifood
    datasource:
        db-kind: postgresql
        devservices:
            enabled: false
        password: marketplace
        username: marketplace
        reactive:
            url: postgresql://${MARKETPLACE_IFOOD_HOST_DB:localhost}:${MARKETPLACE_IFOOD_DB_PORT:5434}/${MARKETPLACE_IFOOD_DB_NAME:ifood-marketplace}
        jdbc: false
    devservices:
        enabled: false
    http:
        port: ${SERVER_PORT:8091}
    flyway:
        migrate-at-start: true
        clean-at-start: true
        default-schema: ifood
        create-schemas: true
    hibernate-orm:
        database:
            default-schema: ifood
amqp-host: localhost
amqp-port: 5672
amqp-username: admin
amqp-password: admin
mp:
    messaging:
        incoming:
            restaurantes:
                connector: smallrye-amqp
                address: restaurantes
        outgoing:
            pedidosKfk:
                connector: smallrye-kafka
                value:
                    serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer